//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonInfoDB_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PokemonInfoTbl
    {
        public int PokedexNo { get; set; }
        public string Category { get; set; }
        public Nullable<double> HeightMetres { get; set; }
        public Nullable<double> WeightKG { get; set; }
        public string Description { get; set; }
        public int Total { get; set; }
        public int HP { get; set; }
        public int Attack { get; set; }
        public int Defense { get; set; }
        public int SpAtk { get; set; }
        public int SpDef { get; set; }
        public int Speed { get; set; }
    }
}
