//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonDB_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PokemonDBEntitiesConnectionString : DbContext
    {
        public PokemonDBEntitiesConnectionString()
            : base("name=PokemonDBEntitiesConnectionString")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PokemonTbl> PokemonTbls { get; set; }
        public virtual DbSet<TrainerTbl> TrainerTbls { get; set; }
    }
}
