//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonDB_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PokemonTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PokemonTbl()
        {
            this.TrainerTbls = new HashSet<TrainerTbl>();
        }
    
        public int PokedexNo { get; set; }
        public string PokemonName { get; set; }
        public string Type1 { get; set; }
        public string Type2 { get; set; }
        public byte[] Image { get; set; }
        public byte[] Image2 { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerTbl> TrainerTbls { get; set; }
    }
}
