//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonDB_MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TrainerTbl
    {
        public int TrainerID { get; set; }

        
        [Required(ErrorMessage = "Please select your name")]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        public string TrainerName { get; set; }

        [Required(ErrorMessage = "Please select your gender")]
        public string Gender { get; set; }

        public int PokedexNo { get; set; }
    
        public virtual PokemonTbl PokemonTbl { get; set; }
    }
}
